parameters:
  - name: environment
    type: string
  - name: business_unit
    type: string
  - name: list
    type: object
    default:
      - here
      - there

stages:
  - stage:
    displayName: Deploy ${{ parameters.environment }}
    jobs:
      - job:
        displayName: Deploy ${{ parameters.environment }}
        steps:
          - script: echo ${{ parameters.business_unit }}
            displayName: show BU
          - script: echo ${{ join(' ', parameters.list) }}