parameters:
  - name: list
    type: object
    default:
      - here
      - there
  - name: env
    type: object
    default:
      here: there
      there: here

stages:
  - stage:
    displayName: Deploy
    variables:
      - group: base
      - group: dev

    jobs:
      - job:
        displayName: Deploy Env
        steps:
          - script: echo $(business_unit)
            displayName: show BU

          - script: echo ${{ join(' ', parameters.list) }}
            displayName: show list

          - task: Bash@3
            displayName: Show dynamic env
            env: ${{ parameters.env }}
            inputs:
              targetType: inline
              script: |
                echo $(environment)
                echo $(ENVIRONMENT)
                echo $(business_unit)
                echo $(BUSINESS_UNIT)
                env              
