parameters:
  - name: environment
    type: string
  - name: business_unit
    type: string

stages:
  - stage:
    displayName: Deploy ${{ parameters.environment }}
    jobs:
      - job:
        displayName: Deploy ${{ parameters.environment }}
        steps:
          - script: echo ${{ parameters.business_unit }}