stages:
  - template: arm.yml
    parameters:
      script:
        path: to/the/script
        globalVars:
          - --x=y,z
          - --supportThings
        globalEnv:
          here=there
          there=here
        localVars:
          - --a=b,c
          - --supportThose